### ISSUE TITLE
IRRd doesn't respond to some queries

### ISSUE THREAD

**Issue by 2bithacker** [irrdnet/irrd#649] opened 2022-05-11 18:03 UTC
**Describe the bug**
Since upgrading to 4.2.4 from 4.0.8 we've been having issues with IRRd becoming unresponsive to some queries. Sometimes IRRd logs `processing query` however it never returns, keeping the socket open, and eventually the whois client times out. During this time, Postgres shows that there are connections open from IRRd, however they are all idle.

We've had some success mitigating this by added `?keepalives=1&keepalives_idle=5` to our `database_url` in our production environment, but the problem intermittently occurs in our dev env, so it would be nice to get a solid fix in place.

**To Reproduce**

In this case, IRRd and Postgres are running locally in docker containers. We can then run `whois` in a loop to query IRRd:

```
> while true; whois -h localhost:8043 '!aAS-65550'; sleep 5; end | env TZ=UTC ts "%Y-%m-%d %H:%M:%.S %Z: "
2022-05-11 17:49:43.128637 UTC:  A35
2022-05-11 17:49:43.128727 UTC:  2607:f3a0:6000::/35 44.190.39.0/24
2022-05-11 17:49:43.128741 UTC:  C
Timeout.
Timeout.
Timeout.
2022-05-11 17:53:03.205163 UTC:  A35
2022-05-11 17:53:03.205359 UTC:  2607:f3a0:6000::/35 44.190.39.0/24
2022-05-11 17:53:03.205452 UTC:  C
2022-05-11 17:53:08.233290 UTC:  A35
2022-05-11 17:53:08.233397 UTC:  2607:f3a0:6000::/35 44.190.39.0/24
2022-05-11 17:53:08.233419 UTC:  C
2022-05-11 17:53:13.276073 UTC:  A35
2022-05-11 17:53:13.276197 UTC:  2607:f3a0:6000::/35 44.190.39.0/24
2022-05-11 17:53:13.276224 UTC:  C
Timeout.
```

And the corresponding logs from IRRd:

```
2022-05-11 17:49:43,111 irrd[24]: [irrd.server.whois.server#DEBUG] ::ffff:100.64.3.1:41978: processing query: !aas-65550
2022-05-11 17:49:43,118 irrd[24]: [irrd.server.whois.server#INFO] ::ffff:100.64.3.1:41978: sent answer to query, elapsed 0.006156124s, 41 bytes: !aas-65550
2022-05-11 17:49:43,118 irrd[24]: [irrd.server.whois.server#DEBUG] ::ffff:100.64.3.1:41978: auto-closed connection
2022-05-11 17:49:48,133 irrd[29]: [irrd.server.whois.server#DEBUG] ::ffff:100.64.3.1:41980: processing query: !aas-65550
2022-05-11 17:50:53,154 irrd[36]: [irrd.server.whois.server#DEBUG] ::ffff:100.64.3.1:41982: processing query: !aas-65550
2022-05-11 17:51:58,163 irrd[33]: [irrd.server.whois.server#DEBUG] ::ffff:100.64.3.1:41984: processing query: !aas-65550
2022-05-11 17:53:03,181 irrd[31]: [irrd.server.whois.server#DEBUG] ::ffff:100.64.3.1:41986: processing query: !aas-65550
2022-05-11 17:53:03,203 irrd[31]: [irrd.server.whois.server#INFO] ::ffff:100.64.3.1:41986: sent answer to query, elapsed 0.021351038s, 41 bytes: !aas-65550
2022-05-11 17:53:03,203 irrd[31]: [irrd.server.whois.server#DEBUG] ::ffff:100.64.3.1:41986: auto-closed connection
2022-05-11 17:53:08,219 irrd[26]: [irrd.server.whois.server#DEBUG] ::ffff:100.64.3.1:41988: processing query: !aas-65550
2022-05-11 17:53:08,232 irrd[26]: [irrd.server.whois.server#INFO] ::ffff:100.64.3.1:41988: sent answer to query, elapsed 0.011830311s, 41 bytes: !aas-65550
2022-05-11 17:53:08,232 irrd[26]: [irrd.server.whois.server#DEBUG] ::ffff:100.64.3.1:41988: auto-closed connection
2022-05-11 17:53:13,255 irrd[35]: [irrd.server.whois.server#DEBUG] ::ffff:100.64.3.1:41990: processing query: !aas-65550
2022-05-11 17:53:13,275 irrd[35]: [irrd.server.whois.server#INFO] ::ffff:100.64.3.1:41990: sent answer to query, elapsed 0.019552186s, 41 bytes: !aas-65550
2022-05-11 17:53:13,275 irrd[35]: [irrd.server.whois.server#DEBUG] ::ffff:100.64.3.1:41990: auto-closed connection
2022-05-11 17:53:18,311 irrd[27]: [irrd.server.whois.server#DEBUG] ::ffff:100.64.3.1:41992: processing query: !aas-65550
2022-05-11 17:54:23,310 irrd[45]: [irrd.server.whois.server#DEBUG] ::ffff:100.64.3.1:41994: processing query: !aas-65550
```

**Expected behaviour**
Expect IRRd to either answer all queries or report some error as to why it isn't answering some of them and not just leave the client hanging.

**IRRd version you are running**
IRRd 4.2.4 with Postgres 14.2

**Additional context**
None.

**Comment by mxsasha** [comment] 2022-06-20 10:51
I have been running a check like this on one of my own setups for a few days, and all queries are answered correctly. From the response of 41 bytes it also looks like your query is quite light.

Is there any other load on this server? Anything in Redis or PostgreSQL logs?

Do the workers that get stuck ever recover? In your log I don't see any further activity from PID 29, 36 and 33, but perhaps the timeframe is short. If they do not recover, or slowly, do they use CPU time while stuck? Large memory consumption? Can you run strace on them to see whether they're making any system calls?

**Comment by mxsasha** [comment] 2022-11-15 15:37
Closing for now as not reproducible and no additional info. Maybe this is actually an instance of #693, but the behaviour here does seem a bit different.

**Comment by 2bithacker** [comment] 2022-11-28 18:44
I've been testing this again on 4.2.6 and it appears to still be happening for us in our testing environment, using docker-compose to run Postgres 14.2, redis 7.0.5, and IRRd 4.2.6.

Nothing else is querying Postgres or Redis. I've enabled query logging in Postgres and it looks normal to me.

It appears that once an IRRd worker gets into this state it never appears in the logs again. I've attached an strace to one and it appears to be stuck in a `select` loop, just repeating `select(0, NULL, NULL, NULL, {tv_sec=1, tv_usec=0}) = 0 (Timeout)`. Not seeing excessive memory or CPU usage.

**Comment by 2bithacker** [comment] 2022-11-28 22:47
All my previous testing was using CPython, just spent some time getting it working with PyPy instead, and the problem still occurs but not nearly as often. It also seems to only affect the first set of workers, once they're locked up, all the new workers seem to work just fine.

I did get strace attached to a stuck PyPy worker and it appears to be stuck in the same select() loop as the CPython worker, so at least that's consistent.

**Comment by mxsasha** [comment] 2022-11-30 11:55
I just added a wiki page with additional debugging tips for these kind of issues: https://github.com/irrdnet/irrd/wiki/Debugging-and-reporting-tips-for-complex-issues

For your strace, which process were you monitoring? Because that select call looks like a one second sleep, it doesn't actually wait for any sockets. We do one second sleeps repeatedly in the main process (and then schedule new tasks every 15 loops).

**Comment by 2bithacker** [comment] 2022-11-30 17:18
I was looking at the pid that logs the "processing query" message:
```
2022-11-30 17:11:27,600 irrd[46]: [irrd.server.whois.server#DEBUG] ::ffff:100.64.35.1:53054: processing query: !aas-65550
```
`ps -uw --pid 46`:
```
USER         PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
daemon        46  0.0  1.3 408060 211964 ?       Sl   17:11   0:00 irrd-whois-worker-::ffff:100.64.35.1:53054
```
`strace -p 46 -s 1000 -tt -yy`:
```
strace: Process 46 attached
17:12:14.146544 select(0, NULL, NULL, NULL, {tv_sec=0, tv_usec=525574}) = 0 (Timeout)
17:12:14.673072 select(0, NULL, NULL, NULL, {tv_sec=1, tv_usec=0}) = 0 (Timeout)
17:12:15.674208 select(0, NULL, NULL, NULL, {tv_sec=1, tv_usec=0}) = 0 (Timeout)
17:12:16.675641 select(0, NULL, NULL, NULL, {tv_sec=1, tv_usec=0}) = 0 (Timeout)
17:12:17.676863 select(0, NULL, NULL, NULL, {tv_sec=1, tv_usec=0}) = 0 (Timeout)
17:12:18.678063 select(0, NULL, NULL, NULL, {tv_sec=1, tv_usec=0}) = 0 (Timeout)
17:12:19.679411 select(0, NULL, NULL, NULL, {tv_sec=1, tv_usec=0}) = 0 (Timeout)
```

**Comment by mxsasha** [comment] 2023-02-17 11:07
Does this still occur sometimes? 4.2.7 and newer respond to SIGUSR1 by logging a traceback of all threads, so that may give extra info.

**Comment by 2bithacker** [comment] 2023-02-18 19:29
Unfortunately my employment situation has changed and I’m no longer in a position to verify this. Can probably close this issue, they can reopen it if the problem is ongoing.

**Comment by mxsasha** [comment] 2023-02-20 22:06
Sorry to hear about the employment situation! Closing this issue then.

**Closed as completed by mxsasha** 2023-02-20 22:06 UTC
