### ISSUE TITLE
some columns are not created

### ISSUE THREAD

**Issue by shibuya-jp** [irrdnet/irrd#514] opened 2021-06-22 07:51 UTC
Hello, I'm an engineer of JPNIC and in the process of evaluation that we can adopt IRRd version 4 as a software for JPIRR in the future.

It seems that IRRd table configuration does not finish as described in the official documentation.
https://irrd4.readthedocs.io/en/master/admins/deployment.html#creating-tables
We believe that the python command file irrd_database_upgrade is meant to execute all the alembic migration processes, namely
```
1743f98a456d_add_serial_newest_mirror.py
181670a62643_add_journal_entry_origin.py
28dc1cd85bdc_initial_db.py
39e4f15ed80c_add_bogon_status.py
4a514ead8fc2_bogon_to_scope_filter.py
64a3d6faf6d4_add_prefix_length_rpki_status_to_rpsl_objects.py
a7766c144d61_add_synchronised_serial_to_database_.py
a8609af97aa3_set_prefix_length_in_existing_rpsl_.py
e07863eac52f_add_roa_object_table.py
```
However, it appears that in our case some of the mandatory attributes (columns in a postgresql table) of rpsl_objects were not created.
To bypass this process we manually executed alembic initialisation and migration and then finally confirmed the creation of the new columns.

**IRRd version you are running**
4.1.2

**Comment by mxsasha** [comment] 2021-06-22 09:55
This sounds like a bug, but a bit puzzling that it hasn't been encountered before.

Database upgrades are logged in the irrd logfile. Could you have a look on what that logged when you ran irrd_database_upgrade? 

And do you remember which columns were missing?

**Comment by shibuya-jp** [comment] 2021-06-22 09:58
Thank you for your confirmation.
Let me get back to you when I can answer for sure.

**Comment by troy2914** [comment] 2021-06-22 20:22
btw, i just tested with a fresh db:  connected to template1,  ran:
```
CREATE DATABASE irrd;
CREATE ROLE irrd WITH LOGIN ENCRYPTED PASSWORD 'irrd';
GRANT ALL PRIVILEGES ON DATABASE irrd TO irrd;
\c irrd
CREATE EXTENSION IF NOT EXISTS pgcrypto;
```

then was able to run 
```
%  irrd_database_upgrade --config irrd.yaml
Upgrade successful, or already on latest version.
```

I was trying this on my mac,  irrd is unhappy about something,  but doesn't seem to be about the db.

btw, highly recommend you upgrade to the latest stable (currently 4.1.4).

**Comment by shibuya-jp** [comment] 2021-06-24 09:33
> 
> 
> This sounds like a bug, but a bit puzzling that it hasn't been encountered before.
> 
> Database upgrades are logged in the irrd logfile. Could you have a look on what that logged when you ran irrd_database_upgrade?
> 
> And do you remember which columns were missing?

I guess alembic didn't make all of the columns assumed to be created.
I encountered the following error mail when trying to create objects and found the problem.

```
psycopg2.errors.UndefinedColumn: column rpsl_objects.rpki_status does not
    exist LINE 1: ...a, rpsl_objects.object_text, rpsl_objects.source,
    rpsl_objec...
```
postgres's log:
```
2021-03-25 10:14:07.396 JST [29561] irrd@irrd ERROR:  column rpsl_objects.rpki_status does not exist at character 147
2021-03-25 10:14:07.396 JST [29561] irrd@irrd STATEMENT:  SELECT rpsl_objects.pk, rpsl_objects.object_class, rpsl_objects.rpsl_pk, rpsl_objects.parsed_data, rpsl_objects.object_text, rpsl_objects.source, rpsl_objects.rpki_status
      FROM rpsl_objects
      WHERE rpsl_objects.source IN ('NEW-SOURCE') AND rpsl_objects.object_class IN ('mntner') AND rpsl_objects.rpsl_pk IN ('TEST_MNTNER') ORDER BY CASE WHEN (rpsl_objects.source = 'NEW-SOURCE') THEN 1 ELSE 100000 END, rpsl_objects.ip_first ASC, rpsl_objects.asn_first ASC, rpsl_objects.rpsl_pk ASC
```
the below is the irrd log when I tried alembic migration.
```
2021-04-01 02:48:55,904 irrd[14729]: [alembic.runtime.migration#INFO] Context impl PostgresqlImpl.
2021-04-01 02:48:55,905 irrd[14729]: [alembic.runtime.migration#INFO] Will assume transactional DDL.
2021-04-01 04:32:23,910 irrd[17456]: [alembic.runtime.migration#INFO] Context impl PostgresqlImpl.
2021-04-01 04:32:23,911 irrd[17456]: [alembic.runtime.migration#INFO] Will assume transactional DDL.
```
the below is the log of succeeding when I  manually executed alembic initialization.
```
2021-04-15 07:11:39,233 irrd[19027]: [alembic.runtime.migration#INFO] Running upgrade 28dc1cd85bdc -> e07863eac52f, Add roa_object table.
2021-04-15 07:11:39,396 irrd[19027]: [alembic.runtime.migration#DEBUG] update 28dc1cd85bdc to e07863eac52f
2021-04-15 07:11:39,398 irrd[19027]: [alembic.runtime.migration#INFO] Running upgrade e07863eac52f -> 64a3d6faf6d4, Add prefix_length and rpki_status to rpsl_objects
2021-04-15 07:11:39,433 irrd[19027]: [alembic.runtime.migration#DEBUG] update e07863eac52f to 64a3d6faf6d4
2021-04-15 07:11:39,434 irrd[19027]: [alembic.runtime.migration#INFO] Running upgrade 64a3d6faf6d4 -> a8609af97aa3, Set prefix_length in existing RPSL objects
2021-04-15 07:11:39,586 irrd[19027]: [alembic.runtime.migration#DEBUG] update 64a3d6faf6d4 to a8609af97aa3
2021-04-15 07:11:39,587 irrd[19027]: [alembic.runtime.migration#INFO] Running upgrade a8609af97aa3 -> 181670a62643, Add journal entry origin
2021-04-15 07:11:39,593 irrd[19027]: [alembic.runtime.migration#DEBUG] update a8609af97aa3 to 181670a62643
2021-04-15 07:11:39,593 irrd[19027]: [alembic.runtime.migration#INFO] Running upgrade 181670a62643 -> 1743f98a456d, Add serial_newest_mirror
2021-04-15 07:11:39,595 irrd[19027]: [alembic.runtime.migration#DEBUG] update 181670a62643 to 1743f98a456d
2021-04-15 07:11:39,596 irrd[19027]: [alembic.runtime.migration#INFO] Running upgrade 1743f98a456d -> 39e4f15ed80c, Add bogon_status
2021-04-15 07:11:39,596 irrd[19027]: [alembic.runtime.migration#DEBUG] update 1743f98a456d to 39e4f15ed80c
2021-04-15 07:11:39,597 irrd[19027]: [alembic.runtime.migration#INFO] Running upgrade 39e4f15ed80c -> 4a514ead8fc2, bogon_to_scopefilter
2021-04-15 07:11:39,652 irrd[19027]: [alembic.runtime.migration#DEBUG] update 39e4f15ed80c to 4a514ead8fc2
2021-04-15 07:11:39,653 irrd[19027]: [alembic.runtime.migration#INFO] Running upgrade 4a514ead8fc2 -> a7766c144d61, Add synchronised_serial to database status
2021-04-15 07:11:39,656 irrd[19027]: [alembic.runtime.migration#DEBUG] update 4a514ead8fc2 to a7766c144d61
```

**Comment by shibuya-jp** [comment] 2021-06-24 09:39
> 
> 
> btw, i just tested with a fresh db: connected to template1, ran:
> 
> ```
> CREATE DATABASE irrd;
> CREATE ROLE irrd WITH LOGIN ENCRYPTED PASSWORD 'irrd';
> GRANT ALL PRIVILEGES ON DATABASE irrd TO irrd;
> \c irrd
> CREATE EXTENSION IF NOT EXISTS pgcrypto;
> ```
> 
> then was able to run
> 
> ```
> %  irrd_database_upgrade --config irrd.yaml
> Upgrade successful, or already on latest version.
> ```
> 
> I was trying this on my mac, irrd is unhappy about something, but doesn't seem to be about the db.
> 
> btw, highly recommend you upgrade to the latest stable (currently 4.1.4).

Thanks for your confirmation.
I'll consider upgrade the version.

Later I found there was a possibility of the different execution environment you assume.
That is; your documents assume this program should be executed under the virtualenv, but I happened to execute under the different pyenv. It might lead to this missing.

If you cannot reproduce this problem, I'd like to report separately when I encountered again. Many thanks!

**Comment by troy2914** [comment] 2021-06-24 11:45
and my empty db does have a rpki_objects.rpki_status field.   what version of irrd were you upgrading from?

**Comment by shibuya-jp** [comment] 2021-06-25 03:18
> 
> 
> and my empty db does have a rpki_objects.rpki_status field. what version of irrd were you upgrading from?

That was from 4.1.1.  We started the evaluation of irrdv4 in October 2020, and I think that was the latest version at that time.
I'm aware this may be too old. Now we review our set-up process and report the issue we met. If you cannot reproduce this matter in the latest version, I don't mind this ticket is closed.

**Comment by troy2914** [comment] 2021-06-25 20:02
Interesting, as 4.1.1 (even 4.1.0) should have that column present.   I have done a 4.0.1 upgrade to 4.1.0 to 4.1.1 to 4.1.2 to 4.1.3rc1 and 4.1.4 with no problems.

**Comment by mxsasha** [comment] 2021-06-27 18:19
I can't reproduce this or explain it. Also, the integration tests run something very close this scenario on every commit. So closing unless we get more info at some point.

**Closed as completed by mxsasha** 2021-06-27 18:19 UTC
