### ISSUE TITLE
Fix support for fail-over through regular mirroring re password hashes

### ISSUE THREAD

**Issue by troy2914** [irrdnet/irrd#533] opened 2021-07-31 10:51 UTC
We were running 4.1.4

Doing maintenance in one location we wanted to fail over to the other location. 
Found out 5 days later that the other location did not have crypt's.  So updates without the override password (or PGPKEYs)
were failing.   Seems for situation like it would be nice to have a trusted_source list, that whois/NRTM/https connections from would not hide the crypt's.

**Comment by mxsasha** [comment] 2021-07-31 11:21
I see the point here. One thing that we definitely need to do is update the migration documentation, as it may affect migrations from legacy IRRd as well.

For PGPKEY, the data is never masked, the issue is only that PGP keys from mirrors are by default not inserted in the local gpg keychain which is used for verifying signatures. That part can be fixed by setting `strict_import_keycert_objects`.

For failover with passwords, having a trusted feed/export could work. It's not terribly hard either. I don't think it's a very pretty solution, but it might just be the best one we have. The root issue is having password hashes in RPSL objects is a poor design choice, but that's not in scope to fix.

If you do failover based on regular IRR mirroring, there are also some important considerations around journals, serials and NRTM. Basically, NRTM mirrors may need to reload their copy of the data from a fresh download, as the journal between the old and new location may be different.

My thoughts for now are to:

- Update the migration documentation regarding password hashes so that people are aware of this potential issue
- Add support for a mirroring export and NRTM that includes auth hashes in some exports / for some clients
- Add new documentation that covers common considerations for failover setups with IRRDv4 and their potential pitfalls - there are a few options here, a few settings that influence scenarios, etc. 

I'll also give some thought to whether there might be a better solution here.

**Comment by tangledhelix** [comment] 2021-07-31 20:54
@mxsasha Whatever you do, we'd like to see it backported to 4.1.x, if that's a possibility.

**Comment by mxsasha** [comment] 2021-08-09 13:57
I've drafted new documentation that outlines the options and their upsides/downsides. The new command and new settings mentioned in there aren't written yet, but it would be good if @troy2914 and/or @tangledhelix could have a look at how this would work: https://irrd.readthedocs.io/en/issue533/admins/availability-and-migration/ and see if that's a good path.

**Comment by troy2914** [comment] 2021-08-09 14:53
That seems reasonable to me.  I wonder though have you actually tested a irrd talking to a readonly db?
Or does that require a `sources_default`  but no `sources`?    or a `sources` with only only limited options(seems there some missing documentation around this).

**Comment by mxsasha** [comment] 2021-08-09 15:40
> That seems reasonable to me. I wonder though have you actually tested a irrd talking to a readonly db?

Not yet, but I will. Rethinking this, it will actually require a specific setting, for IRRd to ignore it in RPKI and scope filtering, which is not possible to configure right now (excluding a source from RPKI or scope filter is possible, but that's different from "never touch the status").

**Comment by mxsasha** [comment] 2021-08-28 17:11
Released in 4.1.5

**Closed as completed by mxsasha** 2021-08-28 17:11 UTC
Labels: release blocker, backport
